[build]
  command = "npm run build:production"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  SUPABASE_URL = "Your Supabase URL"
  SUPABASE_ANON_KEY = "Your Supabase Anon Key"
  STRIPE_PUBLISHABLE_KEY = "Your Stripe Publishable Key"