[dev]
  targetPort = 19006

# Netlify Configuration
[build]
  publish = "dist"
  command = "NODE_ENV=production npm run build:production"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./**/__tests__/**"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  EXPO_PUBLIC_SUPABASE_URL = "$EXPO_PUBLIC_SUPABASE_URL"
  EXPO_PUBLIC_SUPABASE_ANON_KEY = "$EXPO_PUBLIC_SUPABASE_ANON_KEY"
