[build]
  command = "npx expo export -p web --output-dir dist"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/embedded-finance/virtual-cards"
  to = "/.netlify/functions/embedded-finance-virtual-cards"
  status = 200
  force = true

[[redirects]]
  from = "/embedded-finance/virtual-cards/*"
  to = "/.netlify/functions/embedded-finance-virtual-cards/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/stripe/webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  NODE_VERSION = "18"
  EXPO_PUBLIC_SUPABASE_URL = "Your Supabase URL"
  EXPO_PUBLIC_SUPABASE_ANON_KEY = "Your Supabase Anon Key"
  EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY = "Your Stripe Publishable Key"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
